### ISSUE TITLE
"Open a File" dialog looks broken

### ISSUE THREAD

**Issue by mkoloberdin** [kekcleader/FreeOberon#4]
`F3`/`Open a File` shows an empty dialog (see the screenshot below).

If I type in a file name (e.g. Book.Mod) manually it gets opened just fine. If I type in random garbage, nothing happens, no error message etc.

OS: Linux (Arch Linux)
FreeOberon version: 1.0.3 (git tag 9da6825069780259ccec89984ec8281d5189e912)

![Screenshot_20210902_230317](https://user-images.githubusercontent.com/123562/131908943-8fa38128-6078-4e45-b67d-47567c9ce090.png)

**Comment by mkoloberdin** [comment]
Never mind. I've just had a look at the commit history and source code and as far as I understand it, it is just something that is being implemented _after_ the 1.0.3 release.

**Comment by kekcleader** [comment]
@mkoloberdin Hi, thanks for the comment.
Yes, in this version the file dialog is a bit "unfinished", there are no error messages whatsoever.
However, a big update is comming up very soon, with a new file dialog, with a list of files to choose from etc.
Also the new version of Free Oberon can compile isolated programs in other directories, not only in the "Programs" subdirectory. Furthermore, modules of your program can be split into subfolders, i.e. module named "TetrisEngine" may reside in "Tetris/Engine.Mod". So a name consisting of two word may be split in two.
This all works already, I just need to build the new ZIP archives and get them ready for people to download.
In Windows version, Mingw32 is replaced with Mingw-w64, a more modern varioant of GCC for Windows (it also supports 32-bits despite of the name).

I'll prepare a more detailed textual description of the update as soon as it is ready. Hope you will be still there to test.
![Screenshot_File_Dialog_Oberon](https://user-images.githubusercontent.com/2365746/131921631-2092093e-24fb-4271-b60f-c134f07e66b2.png)
