### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by Spoiledpay** [kekcleader/FreeOberon#5]
Esteemed,
there is the option of the ide and compiler in english?
thanks.

**Comment by kekcleader** [comment]
Yes. The IDE and compiler messages can be switched to English by doing the steps outlined below.

Sorry for the inconvenience, the language switcher menu will be included soon in the new version and the default language will be English. The steps are also available on the home page of free.oberon.org and in the readme file:
```
Please run Free Oberon from command line specifying the "en" language:
./FreeOberon --lang en
```

The steps to run Free Oberon in English.

On Windows:
1. Open Command Prompt (the standard Windows utility).
2. Go inside the Free Oberon directory. To do that change drive letter (if required) by typing:
```
D:
```
and change current directory with `cd`:
```
cd FreeOberon
```
3. Run Free Oberon from the command line specifying --lang en as command line parameters:
```
FreeOberon.exe --lang en
```

On Linux:
When you launch FreeOberon make sure to include --lang en
```
./FreeOberon --lang en
```
